### ISSUE TITLE
general fixes on phase 1

### ISSUE THREAD

**Issue by abdelazizElemary** [MuhammadSawalhy/udemy-clone-react#2]
- you need to separate pages in the component folder each in separate folder and all placed in `pages` folder.
- use object destruction as discussed this morning. for example in courses object in CourseCarousel and CourseCard components.
- move tabs constant array in separate constant folder that contains all the constants needed in the project
- enable enlarge on hover in the top categories section

**Comment by MuhammadSawalhy** [comment]
Fixed, but the first point is still not clear.
